# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Designsystem
email: marianne.rosvik@bouvet.no
description: > # this means to ignore newlines until "baseurl:"
  Designsystem for Brønnøysundregistrenes webløsninger
baseurl: "/styleguide" # the subpath of your site, e.g. /blog
url: "altinn.github.io/" # the base hostname & protocol for your site
twitter_username: altinn
github_username:  altinn

# Build settings
markdown: kramdown
